CREATE TABLE JEFEESCUDERIA(
    NOMBRE VARCHAR2(30) CONSTRAINT JEF_NOM_PK PRIMARY KEY,
    FECHANAC DATE CONSTRAINT JEF_FEC_NN NOT NULL,
    PAISORIGEN VARCHAR2(20) CONSTRAINT JEF_PAI_NN NOT NULL,
    EXPERIENCIA NUMBER(3) DEFAULT 0
);

CREATE TABLE ESCUDERIA(
    NOMBRE VARCHAR2(20) CONSTRAINT ESC_NOM_PK PRIMARY KEY,
    JEFE VARCHAR2(30) CONSTRAINT JEF_ESC_FK REFERENCES JEFEESCUDERIA,
    PAISORIGEN VARCHAR2(20) CONSTRAINT ESC_PAI_NN NOT NULL,
    CREACION DATE
);

CREATE TABLE PILOTO(
    NUMLICENCIA NUMBER(8) CONSTRAINT PIL_NUM_PK PRIMARY KEY,
    NOMBRE VARCHAR2(30) CONSTRAINT PIL_NOM_NN NOT NULL,
    PAISORIGEN VARCHAR2(20) CONSTRAINT PIL_PAI_NN NOT NULL,
    FECHANAC DATE CONSTRAINT PIL_FEC_NN NOT NULL,
    CONSTRAINT PIL_NUM_CK CHECK (NUMLICENCIA BETWEEN 10000000 AND 99999999)
);

CREATE TABLE COCHE(
    MODELO VARCHAR2(40) CONSTRAINT COC_MOD_PK PRIMARY KEY,
    ESCUDERIA VARCHAR2(20) CONSTRAINT ESC_COC_FK REFERENCES ESCUDERIA,
    CATEGORIA CHAR(3) CONSTRAINT COC_CAT_NN NOT NULL,
    PESO NUMBER(4) CONSTRAINT COC_PES_NN NOT NULL,
    POTENCIA NUMBER(3) CONSTRAINT COC_POT_NN NOT NULL,
    CONSTRAINT COC_POT_CK CHECK (POTENCIA BETWEEN 300 AND 700),
    CONSTRAINT COC_CAT_CK CHECK (UPPER(CATEGORIA) IN ('GR1', 'GR2', 'GR3', 'GR4')),
    CONSTRAINT COC_POT_CKCP CHECK ((UPPER(CATEGORIA)='GR1' AND POTENCIA BETWEEN 601 AND 700) OR
        (UPPER(CATEGORIA)='GR2' AND POTENCIA BETWEEN 501 AND 600) OR
        (UPPER(CATEGORIA)='GR3' AND POTENCIA BETWEEN 401 AND 500) OR
        (UPPER(CATEGORIA)='GR4' AND POTENCIA BETWEEN 300 AND 400))
);

CREATE TABLE CARRERA(
    CODIGO_CARRERA NUMBER(8) CONSTRAINT CAR_COD_PK PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR2(40),
    AÑO_CARRERA NUMBER(4),
    DURACION VARCHAR2(20)
    CONSTRAINT CAR_DUR_CK CHECK (UPPER(DURACION) LIKE '%VUELTAS' OR UPPER(DURACION) LIKE '%HORAS'),
    MAX_PARTICIPANTES NUMBER(3)
);

CREATE TABLE PARTICIPANTE(
    NUMPARTICIPANTE NUMBER(3),
    CODIGO_CARRERA NUMBER(8) CONSTRAINT CAR_PAR_FK REFERENCES CARRERA,
    COCHE VARCHAR2(40) CONSTRAINT COC_PAR_FK REFERENCES COCHE,
    PILOTOPARTICIPANTE NUMBER(8) CONSTRAINT PIL_PAR_FK1 REFERENCES PILOTO,
    CONSTRAINT PAR_NUC_PK PRIMARY KEY (NUMPARTICIPANTE, CODIGO_CARRERA)
);

DROP TABLE PARTICIPANTE;
DROP TABLE CARRERA;
DROP TABLE COCHE;
DROP TABLE PILOTO;
DROP TABLE ESCUDERIA;
DROP TABLE JEFEESCUDERIA;